[package]
name = "rusttracer"
version = "0.1.0"
authors = ["Jonathan Featherstone <jfeatherstone@instructure.com>"]

[lib]
name = "rtlib"
path = "src/lib.rs"

[[bin]]
name = "rtbin"
path = "src/main.rs"

[dependencies]
